<a href="https://colab.research.google.com/github/Sulthana-2000/Machine-Learning-Classification-Models/blob/main/KNN_Naive_SVM(Heart_Disease).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/heart_missing svm.csv")
df

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1      53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2      70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3      61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4      62    0  0.0       138   294  1.0      1.0      106      0      1.9   
...   ...  ...  ...       ...   ...  ...      ...      ...    ...      ...   
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [23]:
# count of targets by grouping
df1=df.groupby('target')['target'].count()
df1

target
0    499
1    526
Name: target, dtype: int64

In [24]:
#without grouping
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [25]:
df.head()

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1   53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2   70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3   61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4   62    0  0.0       138   294  1.0      1.0      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

In [26]:
df.tail()

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [27]:
df.shape


(1025, 14)

In [28]:
df.dtypes

age           int64
sex           int64
cp          float64
trestbps      int64
chol          int64
fbs         float64
restecg     float64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [29]:
df.isna().sum()

age          0
sex          0
cp           7
trestbps     0
chol         0
fbs         13
restecg      4
thalach      0
exang        0
oldpeak     11
slope        0
ca           0
thal         0
target       0
dtype: int64

In [30]:
mean_cp=df['cp'].mean()
df['cp']=df['cp'].fillna(mean_cp)

mean_fbs=df['fbs'].mean()
df['fbs']=df['fbs'].fillna(mean_fbs)

mean_restecg=df['restecg'].mean()
df['restecg']=df['restecg'].fillna(mean_restecg)

mean_oldpeak=df['oldpeak'].mean()
df['oldpeak']=df['oldpeak'].fillna(mean_oldpeak)

In [31]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [32]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [33]:
y=df.iloc[:,-1].values
y


array([0, 0, 0, ..., 0, 1, 0])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[59.,  1.,  1., ...,  2.,  0.,  2.],
       [58.,  1.,  0., ...,  1.,  3.,  3.],
       [44.,  0.,  2., ...,  1.,  1.,  2.],
       ...,
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [43.,  1.,  0., ...,  2.,  0.,  3.],
       [52.,  1.,  0., ...,  2.,  1.,  2.]])

In [35]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,

In [36]:
x_test

array([[62.,  0.,  0., ...,  2.,  0.,  2.],
       [53.,  0.,  2., ...,  2.,  0.,  0.],
       [55.,  1.,  0., ...,  1.,  1.,  3.],
       ...,
       [70.,  1.,  2., ...,  1.,  1.,  3.],
       [67.,  1.,  0., ...,  1.,  2.,  2.],
       [64.,  1.,  2., ...,  2.,  0.,  2.]])

In [37]:
# Normalization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.51227152,  0.64358464,  0.03400296, ...,  0.97708096,
        -0.72837545, -0.53812812],
       [ 0.40223597,  0.64358464, -0.92715279, ..., -0.65214474,
         2.10991368,  1.10373511],
       [-1.1382618 , -1.55379719,  0.99515871, ..., -0.65214474,
         0.21772092, -0.53812812],
       ...,
       [-0.36801292,  0.64358464, -0.92715279, ...,  0.97708096,
        -0.72837545,  1.10373511],
       [-1.24829735,  0.64358464, -0.92715279, ...,  0.97708096,
        -0.72837545,  1.10373511],
       [-0.25797736,  0.64358464, -0.92715279, ...,  0.97708096,
         0.21772092, -0.53812812]])

In [38]:
# KNN Classification
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)


In [39]:
# Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


In [40]:
# SVM classification
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)


In [41]:
# these three models can be created in one file using "FOR" loop

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score

k_model=KNeighborsClassifier(n_neighbors=7)
n_model=GaussianNB()
s_model=SVC()
lst_model=[k_model,n_model,s_model]

In [42]:
for i in lst_model:
  print("\nModel Name is :",i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("**********************")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy Score.........")
  print(accuracy_score(y_test,y_pred))




Model Name is : KNeighborsClassifier(n_neighbors=7)
**********************
[[127  32]
 [ 16 133]]
Accuracy Score.........
0.8441558441558441

Model Name is : GaussianNB()
**********************
[[119  40]
 [ 19 130]]
Accuracy Score.........
0.8084415584415584

Model Name is : SVC()
**********************
[[134  25]
 [ 11 138]]
Accuracy Score.........
0.8831168831168831
